### ISSUE TITLE
Sometime event seems to be sent multiple times.

### ISSUE THREAD

**Issue by nmDejamobile** [cesarferreira/SwiftEventBus#11]
Even if I only send it once, my registered closure is called multiple times.
So today i have to unregister when receiving the event for the first time.

Note that I'm certain that the posting of the event happens only once, I added a breakpoint and it only stopped once.

Sending:
`SwiftEventBus.post(BUS_EVENT_1_DETECTED, sender: myData)`

Event listener in my view controller viewDidLoad() function :

        SwiftEventBus.onBackgroundThread(self, name:BUS_EVENT_1_DETECTED) { result in
            //listen only once as this event may be casted multiple times.
            SwiftEventBus.unregister(self, name:BUS_EVENT_1_DETECTED)
            let data:MyData = result.object as! MyData
            // then do stuff here with my data.
        } 

Any ideas ?
Thanks.

**Comment by cesarferreira** [comment]
It's the first time I've heard about this issue, This is a wrapper for the `NotificationCenter`, it shouldn't behave like that

**Comment by shshalom** [comment]
@nmDejamobile I've just stumble this issue my self,  the problem is not on the post side but rather on the listening side, seems like NSNotification addObserverForName, just adds the target multiple time for the same key and object regardless its existence.

check if you call SwiftEventBus.onBackgroundThread.. multiple times, e.g. inside table cell.

**Comment by girishghoda** [comment]
@cesarferreira I also face this issue
Sender side not issue but handle side it call multiple time

Thank you
